CREATE TABLE statistics (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    money TEXT(200) NOT NULL,
    bank TEXT(200) NOT NULL,
    vehicles TEXT(200) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);